from typing import Any

class Card:
    ord: Any = ...
    suspend: Any = ...
    def __init__(self, ord: Any, suspend: bool = ...) -> None: ...
    def write_to_db(self, cursor: Any, now_ts: Any, deck_id: Any, note_id: Any) -> None: ...
