from typing import Any, Optional

class Deck:
    deck_id: Any = ...
    name: Any = ...
    description: Any = ...
    notes: Any = ...
    models: Any = ...
    def __init__(self, deck_id: Optional[Any] = ..., name: Optional[Any] = ..., description: str = ...) -> None: ...
    def add_note(self, note: Any) -> None: ...
    def add_model(self, model: Any) -> None: ...
    def to_json(self): ...
    def write_to_db(self, cursor: Any, now_ts: Any) -> None: ...
    def write_to_file(self, file: Any) -> None: ...
    def write_to_collection_from_addon(self) -> None: ...
