from .apkg_col import APKG_COL as APKG_COL
from .apkg_schema import APKG_SCHEMA as APKG_SCHEMA
from .deck import Deck as Deck
from typing import Any, Optional

class Package:
    decks: Any = ...
    media_files: Any = ...
    def __init__(self, deck_or_decks: Optional[Any] = ..., media_files: Optional[Any] = ...) -> None: ...
    def write_to_file(self, file: Any) -> None: ...
    def write_to_db(self, cursor: Any, now_ts: Any) -> None: ...
    def write_to_collection_from_addon(self) -> None: ...
